### PR TITLE
Promises and types

### PR DESCRIPTION
**Pull request by JaceyPenny**
Figured this could use a facelift. I added support for returning promises when a callback is omitted. I also added Typescript typedefs.

LMK what you think!

### CODE REVIEW

**Comment by JaceyPenny** [comment]
@mafintosh forgive the ping!

**Comment by mafintosh** [comment]
Hi. Thanks, appreciate it!

I can't, personally, commit to maintaining a typescript interface for this at this moment. Mb someone other maintainer here has time/knowledge to maintain that? :) Happy to support that if that's the case, or mb you wanna help with the maintenance going forward.

For promises, that's a bigger engineering task ahead of us, for the entire random-access-* / hyper community. I don't think maintaining a dual interface is especially beneficial at this time due to

a) this is a low level module
b) it still exposes a callback interface for implementers (req.callback)
c) it's performance sensitive for the upstream consumers
d) del/write/close callbacks are optional leading to potential unhandled promises upstream

So that part is something that needs to come in a future major release.

**Comment by mafintosh** [comment]
Alternatively a promise only version can be added to a `promises.js` export here so upstream can require that, and then we can switch to that one later once we're ready for that.

**Comment by soyuka** [comment]
Types are a nice addition IMO, for promises, can't it just make use of the new [promisify](https://nodejs.org/api/util.html#util_util_promisify_original) API if needed? Indeed, I don't see much use cases for this API promisifed as maf mentioned it's really low level. 
I'd say that this PR should be splitted in two:
- add types (with callbacks)
- add documentation for the promisify or a new `promise.js` file even though I'm not sure that it adds real value

**Comment by JaceyPenny** [comment]
@mafintosh Ah, I see. I realize now that I wasn't aware of the larger scope of this project and was thinking a bit too much about my personal desires 😆. Knowing that, I agree that having the promises as a main-line feature is a ways off so we'll take that part out for now. I do think the repo could benefit from types, like @soyuka mentioned, so I'll close this PR and re-open another one with types, and link to this discussion.

As for promises, I was absolutely unaware of promisify and I feel like a dunderhead for not knowing about it before now, lol. I am convinced that supporting promises is valuable in a world where async/await reigns. In writing services making use of random-access-* libs, I was struggling to make sense of a lot of the callback hell. I think it would be valuable if I did a performance comparison of the library with-and-without promises and see what effects it has on current implementations as well as performance overhead of promises vs callbacks for this API. I'll leave that for later. I also agree that leaving dangling promises for del/write/close is messy and there's no good way to handle that other than pre-attaching a catch handler... Clearly more thought needs to go there if Promises were to be supported.

Thank you both for your feedback, this was helpful!

**Pull request closed without merging**
