### PR TITLE
Use constants instead of numbers

### PR DESCRIPTION
**Pull request by Gozala**
Optimize readability of the code using names for OP types instead numbers.

### CODE REVIEW

**Review by RangerMauve — APPROVED** [review]
LGTM, I don't have publish rights though. 😁 Definitely more readable.

**Review by martinheidegger — APPROVED** [review]

**Comment by martinheidegger** [comment]
Even though I don't have publish rights, I have merged it as we have two reviews and it seems like a no-brainer. Thanks for the PR.

**Comment by mafintosh** [comment]
fwiw the numbers where there because v8 used to not inline switches when using constants, unsure if that still matters

**Comment by mafintosh** [comment]
@martinheidegger just fyi, force pushed the merge commit away and made it a rebase instead (we forgot to disable the merge btn when setting up the repo, also fixed)

**Comment by mafintosh** [comment]
did some quick tests and it seems that switches are indeed inlined now when using variables

**Comment by martinheidegger** [comment]
@mafintosh Thank you for that insight. And thank you for that check. It would have been good to document these sort of performance details :wink:

**Pull request merged**
